// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Core.Entities.Concrete;
using System;
using System.Collections.Generic;

namespace General.Entities
{
    public partial class Role:Entity
    {
        public Role()
        {
            UserRole = new HashSet<UserRole>();
        }

        public string Name { get; set; }

        public virtual ICollection<UserRole> UserRole { get; set; }
    }
}