// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Core.Entities.Concrete;
using General.Entities.Concrete;
using System;
using System.Collections.Generic;

namespace General.Entities
{
    public partial class User : Entity
    {
        public User()
        {
            UserRoles = new HashSet<UserRole>();
        }

        public long CompanyId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Photo { get; set; }
        public DateTime BirthDate { get; set; }
        public bool Status { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }

        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual Company Company { get; set; }
    }
}